version: '3'
services:
  web:
    build: .
    container_name: stream
    command: tail -f /dev/null
    volumes:
      - .:/stream/
      - /build/
      - /usr/bin/
      - /home/autibequi/.aws:/root/.aws
    ports:
     - "1935:1935"
     - "3000:3000"
     - "80:80"