version: '3'
services:
  web:
    build: .
    privileged: true
    container_name: stream
    entrypoint: tail -f /dev/null
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SESSION_TOKEN
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/stream/
      - /build/
      - /usr/bin/
      - /home/autibequi/.aws:/root/.aws
    ports:
     - "1935:1935"
     - "3000:3000"
     - "80:80"